body:
  - type: markdown
    attributes:
      value: |
        You want Bati to support a specific lib or framework? Great!
        Simply fill in the form below
  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the lib or framework
      placeholder: React
  - type: input
    id: homepage
    attributes:
      label: Homepage
      description: Homepage of the lib or framework
      placeholder: https://react.dev
